### ISSUE TITLE
installation failed (Binary)

### ISSUE THREAD

**Issue by visehra** [intelligent-soft-robots/pam_documentation#1]
I followed the instruction guide shown in:
http://people.tuebingen.mpg.de/mpi-is-software/pam/docs/pam_documentation/doc/A1_overview_and_installation.html

But after executing the line : o80_mujoco the following error accrued:

vsehra@almond:~$ o80_mujoco 
Traceback (most recent call last):
  File "/usr/local/bin/o80_mujoco", line 149, in <module>
    execute()
  File "/usr/local/bin/o80_mujoco", line 123, in execute
    config = configure()
  File "/usr/local/bin/o80_mujoco", line 82, in configure
    pam_models.get_default_config_path(),
  File "/usr/local/lib/python3.8/dist-packages/pam_models/__init__.py", line 29, in get_default_config_path
    return get_config_path("hill")
  File "/usr/local/lib/python3.8/dist-packages/pam_models/__init__.py", line 25, in get_config_path
    raise FileNotFoundError("failed to find pam_models config file "+config_file)
FileNotFoundError: failed to find pam_models config file /opt/mpi-is/pam_models//hill.json

This accrued as the /opt/mpi-is/pam_models/ file is empty

**Comment by vincentberenz** [comment]
@visehra thanks for the issue ! it is important to set assignees to it, otherwise the concerned people will not get notification, and the issue will not be listed in the list of issues they have to take care of. Adding a label is also good.

**Comment by vincentberenz** [comment]
@visehra this should be fixed in the latest tar ball !
